Basic Operations Event input
Ericsson/eiffel-operations-extension pull request #4
Opened 2017-02-02 15:16 UTC by erobged

I have created the basic events and strutures for Eiffel Operations ext

2017-02-03 05:43 UTC, d-stahl-ericsson requested changes

2017-02-03 05:43 UTC, d-stahl-ericsson commented on examples/README.txt
> +l
Remove this?

2017-02-03 05:43 UTC, d-stahl-ericsson commented on eiffel-vocabulary/EiffelArtifactDeployedEvent.md
> +__Description:__ The location at which the artifact is deployed.
This doesn't make any sense. Is it a reason or a location? And I would have thought we'd use an ENVIRONMENT reference for the location?

2017-02-03 05:43 UTC, d-stahl-ericsson commented on eiffel-vocabulary/EiffelConfigurationOrderedEvent.md
> +__Description:__ The EiffeliConfigurationOrderedEvent declares that a configuration has been Ordered.
Copy-paste error? I'm wondering what's up with all these data.reason fields, why are they really there?

2017-02-03 05:43 UTC, d-stahl-ericsson commented on eiffel-vocabulary/EiffelServiceResumedEvent.md
> +The EiffelServiceResumedEvent declares that a service has been Resumed and is ready for use.
Perhaps be a bit more descriptive here, explaining the relationship to ServicePaused and ServiceStarted? Being more verbose in the event descriptions is a general comments for all event types.

2017-02-03 05:43 UTC, d-stahl-ericsson commented on examples/events/EiffelServiceStartedEvent/simple.json
> +      }
This needs to reference an artifact deployment, too, wouldn't you agree? Yes, you can infer what the service is by looking at what has been deployed to the environment, but it's better to be explicit. Besides, consider the scenario where a single host (the ENVIRONMENT) holds a number of services. You want to be particular about which one this is about.

2017-02-06 11:15 UTC, erobged commented on examples/README.txt
> +l
I removed this file.....

2017-02-06 11:19 UTC, erobged commented on eiffel-vocabulary/EiffelArtifactDeployedEvent.md
> +__Description:__ The location at which the artifact is deployed.
Hi Daniel, you are correct this does not make sense. This work I have done is essentially a dump of any data to get me started ( a skeleton of an event) . Any data in these events is probably wrong and lots of data is obviously missing.  my intent was to get something "in" the events to get me started that's all.

2017-02-06 11:20 UTC, erobged commented on eiffel-vocabulary/EiffelConfigurationOrderedEvent.md
> +__Description:__ The EiffeliConfigurationOrderedEvent declares that a configuration has been Ordered.
same as above .,...  the data.reason is not accurate and simple filler to get me started.

2017-02-06 11:50 UTC, erobged commented on eiffel-vocabulary/EiffelServiceResumedEvent.md
> +The EiffelServiceResumedEvent declares that a service has been Resumed and is ready for use.
thanks, I have made an update..
"The EiffelServiceResumedEvent declares that a service has been Resumed from a machine or human instructed Paused state (EiffelServicePausedEvent) and is now available once again for use."

2017-02-06 12:30 UTC, erobged commented on examples/events/EiffelServiceStartedEvent/simple.json
> +      }
Yes , quite right,  
How would I acheive this .
Would this be acheived by using a links Object to the artifact deployment?
Or would this best acheived in a data Object ?
Or both ?

2017-02-06 12:31 UTC, erobged commented
Hi Daniel ,
I responed to your comments.
Regard,s
Rob

2017-02-06 12:40 UTC, erobged commented on examples/events/EiffelServiceStartedEvent/simple.json
> +      }
Would this be heading in the right direction ,
    "links": [
      {
      "type": "ENVIRONMENT",
      "target": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeee0"
      "type": "ARTIFACT",
      "target": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeee1"

      }
  ]
}

2017-02-07 07:05 UTC, d-stahl-ericsson commented
So is this a good time to review changes, or should I wait? :)

2017-02-07 08:03 UTC, erobged commented
Yes please do.
It would be good to have input before we meet later.
This is all new to me so any help is very welcome.

2017-02-07 12:08 UTC, d-stahl-ericsson commented
On a general note, it's typically better to make smaller, more focused commit. I would actually recommend that you split this one up, because it's becoming unmanageable :)

1) Use GitHub issues to plan your work. E.g. create an issue saying "Define EiffelServiceResumedEvent".
2) Create a specific branch in your local repository for it.
3) Make the changes.
4) Push to your private GitHub repo.
5) Make a PR for that particular issue and reference it in the PR comment.

I created a couple of issues the other week. I'll help you get started with Travis and schemas.

2017-02-07 12:17 UTC, d-stahl-ericsson approved these changes

2017-02-07 12:23 UTC, d-stahl-ericsson requested changes

2017-02-07 12:23 UTC, d-stahl-ericsson commented on examples/events/EiffelServiceStartedEvent/simple.json
> +      "target": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeee0"
Missing comma at end of line.

2017-02-07 12:23 UTC, d-stahl-ericsson commented on examples/events/EiffelServiceStoppedEvent/simple.json
> +      "target": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeee5"
Missing comma at end of line.

2017-02-07 12:23 UTC, d-stahl-ericsson commented on eiffel-vocabulary/EiffelArtifactDeployedEvent.md
> +The EiffelArtifactDeployedEvent declares that a software artifact (declared by EiffelArtifactCreatedEvent) has been deployed into an Environemnt (declared by EiffelEnvironmentDefinedEvent) and is con
As a service to the reader, make the referred to events into links.

2017-02-07 12:23 UTC, d-stahl-ericsson commented on eiffel-vocabulary/EiffelConfigurationOrderedEvent.md
> +The EiffeliConfigurationOrderedEvent declares that a configuration has been Ordered.
Could you elaborate on what that means, exactly? How does it relate to ConfigurationApplied?

2017-02-07 12:23 UTC, d-stahl-ericsson commented on eiffel-vocabulary/EiffelConfigurationOrderedEvent.md
> +The EiffeliConfigurationOrderedEvent declares that a configuration has been Ordered.
Why is Ordered capitalized?

2017-02-07 12:23 UTC, d-stahl-ericsson commented on eiffel-vocabulary/EiffelServicePausedEvent.md
> +The EiffelServicePausedEvent declares that a service has been paused .
Additional space before period at end of line.

2017-02-07 12:23 UTC, d-stahl-ericsson commented on eiffel-vocabulary/EiffelServicePausedEvent.md
> +The EiffelServicePausedEvent declares that a service has been paused .
Please elaborate on what pausing means in this context, and why you would want to do that.

2017-02-07 12:23 UTC, d-stahl-ericsson commented on eiffel-vocabulary/EiffelServiceResumedEvent.md
> +The EiffelServiceResumedEvent declares that a service has been Resumed and is ready for use.
Why is Resumed capitalized?

2017-02-07 12:23 UTC, d-stahl-ericsson commented on eiffel-vocabulary/EiffelServiceStartedEvent.md
> +The EiffelServiceStartedEvent declares that a service has been started and is ready for use.
I think this could be elaborated, as it isn't obvious what the relationship is between ServiceStarted and ArtifactDeployed.

2017-02-07 12:57 UTC, erobged commented on examples/events/EiffelServiceStartedEvent/simple.json
> +      "target": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeee0"
This is now fixed .

2017-02-07 12:58 UTC, erobged commented on examples/events/EiffelServiceStoppedEvent/simple.json
> +      "target": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeee5"
This is now fixed .

2017-02-07 13:07 UTC, erobged commented on eiffel-vocabulary/EiffelArtifactDeployedEvent.md
> +The EiffelArtifactDeployedEvent declares that a software artifact (declared by EiffelArtifactCreatedEvent) has been deployed into an Environemnt (declared by EiffelEnvironmentDefinedEvent) and is con
need clarification please;
In the simple.json for the EiffelArtifactDeployedEvent.md I have created two links.
  "links": [
    {
      "type": "ENVIRONMENT",
      "target": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeee0",
    },
    {
      "type": "ARTIFACT",
      "target": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeee3",
    }
  ]
}
  ]
}

and/or do you want me to clarify in the description ?
i.e  
from 
software artifact (declared by EiffelArtifactCreatedEvent)
to
software artifact (linked by EiffelArtifactCreatedEvent) ?

2017-02-07 13:25 UTC, erobged commented on eiffel-vocabulary/EiffelConfigurationOrderedEvent.md
> +The EiffeliConfigurationOrderedEvent declares that a configuration has been Ordered.
I have add more clarity to the description

__Description:__ The EiffeliConfigurationOrderedEvent declares that a new configuration has been ordered and is awaiting implementation. This event is followed by EiffelConfigurationAppliedEvent.

"Ordered" is now "ordered"

2017-02-07 13:25 UTC, erobged commented on eiffel-vocabulary/EiffelServicePausedEvent.md
> +The EiffelServicePausedEvent declares that a service has been paused .
Resolved

2017-02-07 13:27 UTC, erobged commented on eiffel-vocabulary/EiffelServicePausedEvent.md
> +The EiffelServicePausedEvent declares that a service has been paused .
In a change management context we pause the service to push a change to the configuration.
__Description:__ The EiffelServicePausedEvent declares that a service has been set in Paused State intentionally by a human or a machine. The preceeding event state is the EiffelServiceStartedEvent.The subsequent event state is the EiffelServiceResumedEvent.

2017-02-07 13:28 UTC, erobged commented on eiffel-vocabulary/EiffelServiceResumedEvent.md
> +The EiffelServiceResumedEvent declares that a service has been Resumed and is ready for use.
fixed.

2017-02-07 17:05 UTC, erobged commented on eiffel-vocabulary/EiffelServiceStartedEvent.md
> +The EiffelServiceStartedEvent declares that a service has been started and is ready for use.
Clarified some more...
____Description:__ The EiffelServiceStartedEvent declares that a service contained within a defined environment (declared by EiffelEnvironmentDefinedEvent) been started successfully and is ready for use.

2017-02-07 17:35 UTC, erobged commented
responded to all comments.

2017-02-08 06:38 UTC, d-stahl-ericsson commented
Is it ok if I close this PR as per our previous converstaion?

2017-02-08 09:07 UTC, erobged commented
yes , please do.

2017-02-08 10:47 UTC, closed without merging